[meta]
  title = "Live Node Starter"
  description = "Basic demo for using Deepgram to transcribe microphone audio in Node.js" # update with usecase and framework
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)" # update for author details
  useCase = "Live"
  language = "JavaScript"
  framework = "Node"

[build]
  command = "npm install"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `npm run start` to get up and running." # message to give users once setup is complete
